// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Hu3Xdhd5Y2Z2FCAQz7OWl2iepan7WWQ',
    appId: '1:810748913970:web:b17d9fd2ac941e8ccecf2b',
    messagingSenderId: '810748913970',
    projectId: 'fir-task-736b2',
    authDomain: 'fir-task-736b2.firebaseapp.com',
    storageBucket: 'fir-task-736b2.firebasestorage.app',
    measurementId: 'G-VC0ZDJ8L2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJWJXUgpDI41-natF6GjeHkEZ2NY7lHQ',
    appId: '1:810748913970:android:61ddc491198d4602cecf2b',
    messagingSenderId: '810748913970',
    projectId: 'fir-task-736b2',
    storageBucket: 'fir-task-736b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfTXmj60rwQ8xJ6DkInI9t7Nh7h1dC2Q',
    appId: '1:810748913970:ios:6bd2f0c860f93469cecf2b',
    messagingSenderId: '810748913970',
    projectId: 'fir-task-736b2',
    storageBucket: 'fir-task-736b2.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEfTXmj60rwQ8xJ6DkInI9t7Nh7h1dC2Q',
    appId: '1:810748913970:ios:6bd2f0c860f93469cecf2b',
    messagingSenderId: '810748913970',
    projectId: 'fir-task-736b2',
    storageBucket: 'fir-task-736b2.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Hu3Xdhd5Y2Z2FCAQz7OWl2iepan7WWQ',
    appId: '1:810748913970:web:ae47b98c13d2560ccecf2b',
    messagingSenderId: '810748913970',
    projectId: 'fir-task-736b2',
    authDomain: 'fir-task-736b2.firebaseapp.com',
    storageBucket: 'fir-task-736b2.firebasestorage.app',
    measurementId: 'G-DPJ5XGKMW9',
  );
}
